# StockSub 装饰器配置文件
# 用于定义不同环境下的装饰器策略

# 开发环境配置
development:
  provider_decorators:
    decorators:
      - type: frequency_control
        enabled: true
        priority: 1
        config:
          min_interval_ms: 200  # 开发环境较宽松的限制
          max_retries: 3
          enabled: true
      
      - type: circuit_breaker
        enabled: true
        priority: 2
        config:
          name: "DevelopmentStockProvider"
          max_requests: 5
          interval: "60s"
          timeout: "30s"
          ready_to_trip: 5
          enabled: true

# 生产环境配置
production:
  provider_decorators:
    decorators:
      - type: frequency_control
        enabled: true
        priority: 1
        config:
          min_interval_ms: 5000  # 生产环境更保守
          max_retries: 3
          enabled: true
      
      - type: circuit_breaker
        enabled: true
        priority: 2
        config:
          name: "ProductionStockProvider"
          max_requests: 3       # 更严格的熔断策略
          interval: "120s"
          timeout: "60s"
          ready_to_trip: 3      # 更敏感的阈值
          enabled: true

# 测试环境配置
test:
  provider_decorators:
    decorators:
      - type: frequency_control
        enabled: false        # 测试时关闭频率限制
        priority: 1
        config:
          enabled: false
      
      - type: circuit_breaker
        enabled: false        # 测试时关闭熔断器
        priority: 2
        config:
          enabled: false

# 监控环境配置（用于长期监控）
monitoring:
  provider_decorators:
    decorators:
      - type: frequency_control
        enabled: true
        priority: 1
        config:
          min_interval_ms: 3000  # 适合长期监控的频率
          max_retries: 5         # 更多的重试次数
          enabled: true
      
      - type: circuit_breaker
        enabled: true
        priority: 2
        config:
          name: "MonitoringStockProvider"
          max_requests: 10       # 更宽松的熔断策略
          interval: "300s"       # 5分钟统计窗口
          timeout: "120s"        # 2分钟超时
          ready_to_trip: 10      # 更高的阈值
          enabled: true
